//
//  Store.swift
//  InAppKit
//
//  The Store protocol - core domain concept.
//  "My app has a Store where users can buy products"
//
//  Tests use MockStore (auto-generated by @Mockable).
//

import StoreKit
import Mockable

/// The Store - where users buy products.
/// This is the core domain concept from developer's mental model.
@Mockable
public protocol Store: Sendable {
    /// Get available products from the store
    func products(for ids: Set<String>) async throws -> [Product]

    /// Purchase a product
    func purchase(_ product: Product) async throws -> PurchaseOutcome

    /// Get what the user has purchased (their entitlements)
    func purchases() async throws -> Set<String>

    /// Restore previous purchases
    func restore() async throws -> Set<String>
}

/// Result of a purchase - simple domain model
public enum PurchaseOutcome: Equatable, Sendable {
    case success(productId: String)
    case cancelled
    case pending
}
