//
//  StoreKitProvider.swift
//  InAppKit
//
//  Protocol abstracting StoreKit static methods.
//  Like claudebar's CLIExecutor - allows testing infrastructure code.
//  Tests use MockStoreKitProvider (auto-generated by @Mockable).
//

import StoreKit
import Mockable

/// Abstracts StoreKit static methods for testability.
/// This is the lowest level - wraps actual Apple APIs.
@Mockable
public protocol StoreKitProvider: Sendable {
    /// Fetch products from App Store (wraps Product.products(for:))
    func fetchProducts(for ids: Set<String>) async throws -> [Product]

    /// Get current entitlements (wraps Transaction.currentEntitlements)
    func currentEntitlements() async throws -> [VerificationResult<Transaction>]

    /// Sync with App Store (wraps AppStore.sync())
    func sync() async throws
}

/// Default implementation using real StoreKit APIs.
public final class DefaultStoreKitProvider: StoreKitProvider, @unchecked Sendable {

    public init() {}

    public func fetchProducts(for ids: Set<String>) async throws -> [Product] {
        try await Product.products(for: ids)
    }

    public func currentEntitlements() async throws -> [VerificationResult<Transaction>] {
        var results: [VerificationResult<Transaction>] = []
        for await result in Transaction.currentEntitlements {
            results.append(result)
        }
        return results
    }

    public func sync() async throws {
        try await StoreKit.AppStore.sync()
    }
}
