//
//  SubscriptionMemoryRepository.swift
//  InAppKit
//
//  Domain protocol for subscription memory persistence.
//  Tests use MockSubscriptionMemoryRepository (auto-generated by @Mockable).
//

import Foundation
import Mockable

@Mockable
public protocol SubscriptionMemoryRepository: Sendable {
    func load() async throws -> SubscriptionMemory
    func save(_ memory: SubscriptionMemory) async throws
    func clear() async throws
}
