//
//  SubscriptionMemoryStore.swift
//  InAppKit
//
//  Domain protocol for subscription memory persistence.
//  Tests use MockSubscriptionMemoryStore (auto-generated by @Mockable).
//

import Foundation
import Mockable

@Mockable
public protocol SubscriptionMemoryStore: Sendable {
    func load() async throws -> SubscriptionMemory
    func save(_ memory: SubscriptionMemory) async throws
    func clear() async throws
}
